services:
  app:
    container_name: pr_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_DYNAMODB_URL=${AWS_DYNAMODB_URL:-http://pr_dynamodb:8000}
      - AWS_DYNAMODB_REGION=${AWS_DYNAMODB_REGION:-us-east-1}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-dummy}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY:-dummy}
    networks:
      - pr_network
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local:3.0.0
    container_name: prdynamodb
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb
    networks:
      - pr_network

  dynamodb-init:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    container_name: pr_dynamo_init
    networks:
      - pr_network
    entrypoint: >
      aws dynamodb create-table --table-name users --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --region us-east-1 --endpoint-url http://prdynamodb:8000

networks:
  pr_network:
    internal: false
