spring:
  cloud:
    aws:
      dynamodb:
        url: ${AWS_DYNAMODB_URL}
        region: ${AWS_DYNAMODB_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

  application:
    name: PraesidiumAPI